@startuml
'https://plantuml.com/deployment-diagram

entity deliveryAgent_1
entity deliveryAgent_2

node updateLocationMS

node queryNearByMS

node redis

database database

queue kafka_location_update

deliveryAgent_1 --> updateLocationMS

deliveryAgent_2 --> updateLocationMS

updateLocationMS --> redis

queryNearByMS --> redis
updateLocationMS --> kafka_location_update

kafka_location_update --> database

@enduml